import React from 'react';

import {
  Document,
  Image,
  Page,
  Text,
  View,
} from '@react-pdf/renderer';

import {
  pdfStyles,
} from './DailyReportPdfStyles';

import {
  buildPhotoCaption,
  calculateAttachmentTotals,
  calculateEquipmentTotals,
  calculateIssueTotals,
  calculateMaterialTotals,
  calculateWorkforceTotals,
  calculateWorkPeriod,
  formatApprovalAction,
  formatDate,
  formatDateTime,
  formatFileSize,
  formatIssueStatus,
  formatIssueType,
  formatMovementType,
  formatNoteCategory,
  formatNumber,
  formatOperatingStatus,
  formatPercentage,
  formatPpeCompliance,
  formatProductionImpact,
  formatProductionStatus,
  formatQuantity,
  formatReportNumber,
  formatReportStatus,
  formatSafetyStatus,
  formatSeverity,
  formatSiteCondition,
  formatTime,
  formatWeatherCondition,
  formatWindCondition,
  getPhotoSource,
  getPhotoTitle,
  getProductionProgress,
  getTemperatureLabel,
  getVariance,
  safeText,
  shortUserId,
  sortWeatherPeriods,
  splitAttachments,
} from './helpers';

function PageHeader({
  report,
  project,
}) {
  const status =
    report?.status ||
    'draft';

  let statusStyle =
    pdfStyles.statusDraft;

  if (
    status ===
    'submitted'
  ) {
    statusStyle =
      pdfStyles.statusSubmitted;
  }

  if (
    status ===
    'reviewed'
  ) {
    statusStyle =
      pdfStyles.statusReviewed;
  }

  if (
    status ===
    'approved'
  ) {
    statusStyle =
      pdfStyles.statusApproved;
  }

  return (
    <View
      style={
        pdfStyles.header
      }
    >
      <View
        style={
          pdfStyles.headerTopRow
        }
      >
        <View
          style={
            pdfStyles.brandBlock
          }
        >
          <Text
            style={
              pdfStyles.brandName
            }
          >
            RitsuFlow™
          </Text>

          <Text
            style={
              pdfStyles.brandSubtitle
            }
          >
            Daily Report
          </Text>
        </View>

        <Text
          style={
            pdfStyles.documentBadge
          }
        >
          Daily Report
        </Text>
      </View>

      <View
        style={
          pdfStyles.titleRow
        }
      >
        <View
          style={
            pdfStyles.titleBlock
          }
        >
          <Text
            style={
              pdfStyles.reportTitle
            }
          >
            {safeText(
              project?.name,
              'Project Daily Report'
            )}
          </Text>

          <Text
            style={
              pdfStyles.reportSubtitle
            }
          >
            {safeText(
              project?.code,
              'No project code'
            )}
            {' · '}
            {formatReportNumber(
              report?.report_number
            )}
            {' · '}
            {formatDate(
              report?.report_date
            )}
          </Text>
        </View>

        <Text
          style={[
            pdfStyles.statusBadge,
            statusStyle,
          ]}
        >
          {formatReportStatus(
            status
          )}
        </Text>
      </View>
    </View>
  );
}

function Footer({
  report,
}) {
  return (
    <View
      fixed
      style={
        pdfStyles.footer
      }
    >
      <Text
        style={
          pdfStyles.footerText
        }
      >
        Generated by RitsuFlow™ ·{' '}
        {formatReportNumber(
          report?.report_number
        )}
      </Text>

      <Text
        render={({
          pageNumber,
          totalPages,
        }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
        style={
          pdfStyles.footerPage
        }
      />
    </View>
  );
}

function SectionHeader({
  number,
  title,
  description,
}) {
  return (
    <View
      style={
        pdfStyles.sectionHeader
      }
    >
      <Text
        style={
          pdfStyles.sectionEyebrow
        }
      >
        {number} ·{' '}
        {title.toUpperCase()}
      </Text>

      <Text
        style={
          pdfStyles.sectionTitle
        }
      >
        {title}
      </Text>

      {description && (
        <Text
          style={
            pdfStyles.sectionDescription
          }
        >
          {description}
        </Text>
      )}
    </View>
  );
}

function SummaryCard({
  label,
  value,
  helper,
  tone,
}) {
  let innerStyle =
    pdfStyles.summaryCardInner;

  let valueStyle =
    pdfStyles.summaryValue;

  if (
    tone ===
    'success'
  ) {
    innerStyle = [
      pdfStyles.summaryCardInner,
      pdfStyles.summaryCardSuccess,
    ];

    valueStyle = [
      pdfStyles.summaryValue,
      pdfStyles.summaryValueSuccess,
    ];
  }

  if (
    tone ===
    'warning'
  ) {
    innerStyle = [
      pdfStyles.summaryCardInner,
      pdfStyles.summaryCardWarning,
    ];

    valueStyle = [
      pdfStyles.summaryValue,
      pdfStyles.summaryValueWarning,
    ];
  }

  if (
    tone ===
    'danger'
  ) {
    innerStyle = [
      pdfStyles.summaryCardInner,
      pdfStyles.summaryCardDanger,
    ];

    valueStyle = [
      pdfStyles.summaryValue,
      pdfStyles.summaryValueDanger,
    ];
  }

  return (
    <View
      style={
        pdfStyles.summaryCard
      }
    >
      <View
        style={
          innerStyle
        }
      >
        <Text
          style={
            pdfStyles.summaryLabel
          }
        >
          {label}
        </Text>

        <Text
          style={
            valueStyle
          }
        >
          {safeText(
            value
          )}
        </Text>

        {helper && (
          <Text
            style={
              pdfStyles.summaryHelper
            }
          >
            {helper}
          </Text>
        )}
      </View>
    </View>
  );
}

function InfoBox({
  label,
  value,
  width = 'half',
}) {
  let wrapperStyle =
    pdfStyles.infoCellHalf;

  if (
    width ===
    'third'
  ) {
    wrapperStyle =
      pdfStyles.infoCellThird;
  }

  if (
    width ===
    'quarter'
  ) {
    wrapperStyle =
      pdfStyles.infoCellQuarter;
  }

  return (
    <View
      style={
        wrapperStyle
      }
    >
      <View
        style={
          pdfStyles.infoBox
        }
      >
        <Text
          style={
            pdfStyles.infoLabel
          }
        >
          {label}
        </Text>

        <Text
          style={
            pdfStyles.infoValue
          }
        >
          {safeText(
            value
          )}
        </Text>
      </View>
    </View>
  );
}

function TextBox({
  label,
  value,
}) {
  if (!value) {
    return null;
  }

  return (
    <View
      style={
        pdfStyles.textBox
      }
    >
      <Text
        style={
          pdfStyles.textBoxTitle
        }
      >
        {label}
      </Text>

      <Text
        style={
          pdfStyles.textBoxContent
        }
      >
        {value}
      </Text>
    </View>
  );
}

function EmptyState({
  title,
  text,
}) {
  return (
    <View
      style={
        pdfStyles.emptyState
      }
    >
      <Text
        style={
          pdfStyles.emptyStateTitle
        }
      >
        {title}
      </Text>

      <Text
        style={
          pdfStyles.emptyStateText
        }
      >
        {text}
      </Text>
    </View>
  );
}

function TableRow({
  children,
  alternate,
}) {
  return (
    <View
      wrap={false}
      style={[
        pdfStyles.tableRow,
        alternate
          ? pdfStyles.tableRowAlternate
          : null,
      ]}
    >
      {children}
    </View>
  );
}

function TableCell({
  children,
  width,
  strong,
  tone,
}) {
  let style = [
    pdfStyles.tableCell,
    {
      width,
    },
  ];

  if (strong) {
    style.push(
      pdfStyles.tableCellStrong
    );
  }

  if (
    tone ===
    'success'
  ) {
    style.push(
      pdfStyles.tableCellSuccess
    );
  }

  if (
    tone ===
    'warning'
  ) {
    style.push(
      pdfStyles.tableCellWarning
    );
  }

  if (
    tone ===
    'danger'
  ) {
    style.push(
      pdfStyles.tableCellDanger
    );
  }

  return (
    <Text
      style={
        style
      }
    >
      {safeText(
        children
      )}
    </Text>
  );
}

function HeaderCell({
  children,
  width,
}) {
  return (
    <Text
      style={[
        pdfStyles.tableHeaderCell,
        {
          width,
        },
      ]}
    >
      {children}
    </Text>
  );
}

function GeneralSection({
  report,
  project,
}) {
  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="01"
        title="General Information"
      />

      <View
        style={
          pdfStyles.infoGrid
        }
      >
        <InfoBox
          label="Project"
          value={
            project?.name
          }
        />

        <InfoBox
          label="Project Code"
          value={
            project?.code
          }
        />

        <InfoBox
          label="Report Number"
          value={
            formatReportNumber(
              report?.report_number
            )
          }
        />

        <InfoBox
          label="Report Date"
          value={
            formatDate(
              report?.report_date
            )
          }
        />

        <InfoBox
          label="Work Start"
          value={
            formatTime(
              report?.work_start_time
            )
          }
        />

        <InfoBox
          label="Work End"
          value={
            formatTime(
              report?.work_end_time
            )
          }
        />

        <InfoBox
          label="Work Period"
          value={
            calculateWorkPeriod(
              report?.work_start_time,
              report?.work_end_time
            )
          }
        />

        <InfoBox
          label="Status"
          value={
            formatReportStatus(
              report?.status
            )
          }
        />
      </View>

      <TextBox
        label="General Notes"
        value={
          report?.general_notes
        }
      />
    </View>
  );
}

function WeatherSection({
  weather,
}) {
  const rows =
    sortWeatherPeriods(
      weather
    );

  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="02"
        title="Weather & Site Conditions"
      />

      {rows.length ===
      0 ? (
        <EmptyState
          title="No weather records"
          text="No weather or site condition information was recorded for this Daily Report."
        />
      ) : (
        <View
          style={
            pdfStyles.table
          }
        >
          <View
            style={
              pdfStyles.tableHeader
            }
          >
            <HeaderCell width="12%">
              Period
            </HeaderCell>

            <HeaderCell width="18%">
              Condition
            </HeaderCell>

            <HeaderCell width="15%">
              Temp.
            </HeaderCell>

            <HeaderCell width="13%">
              Wind
            </HeaderCell>

            <HeaderCell width="14%">
              Site
            </HeaderCell>

            <HeaderCell width="15%">
              Impact
            </HeaderCell>

            <HeaderCell width="13%">
              Hours
            </HeaderCell>
          </View>

          {rows.map(
            (
              item,
              index
            ) => (
              <TableRow
                key={
                  item.id ||
                  `${item.period}-${index}`
                }
                alternate={
                  index % 2 ===
                  1
                }
              >
                <TableCell
                  width="12%"
                  strong
                >
                  {safeText(
                    item.period
                  )}
                </TableCell>

                <TableCell width="18%">
                  {formatWeatherCondition(
                    item.condition ||
                      item.weather_condition
                  )}
                </TableCell>

                <TableCell width="15%">
                  {getTemperatureLabel(
                    item.temperature_min ??
                      item.temperature,
                    item.temperature_max,
                    item.temperature_unit
                  )}
                </TableCell>

                <TableCell width="13%">
                  {formatWindCondition(
                    item.wind_condition
                  )}
                </TableCell>

                <TableCell width="14%">
                  {formatSiteCondition(
                    item.site_condition
                  )}
                </TableCell>

                <TableCell
                  width="15%"
                  tone={
                    item.production_impact &&
                    item.production_impact !==
                      'none'
                      ? 'warning'
                      : undefined
                  }
                >
                  {formatProductionImpact(
                    item.production_impact
                  )}
                </TableCell>

                <TableCell width="13%">
                  {formatNumber(
                    item.impact_hours,
                    {
                      maximumFractionDigits:
                        1,
                    }
                  )}
                </TableCell>
              </TableRow>
            )
          )}
        </View>
      )}
    </View>
  );
}

function WorkforceSection({
  workforce,
}) {
  const totals =
    calculateWorkforceTotals(
      workforce
    );

  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="03"
        title="Workforce"
      />

      <View
        style={
          pdfStyles.summaryGrid
        }
      >
        <SummaryCard
          label="Crews"
          value={
            totals.crews
          }
        />

        <SummaryCard
          label="Workers"
          value={
            totals.workers
          }
          tone="success"
        />

        <SummaryCard
          label="Regular Labor-Hours"
          value={
            formatNumber(
              totals.regularLaborHours,
              {
                maximumFractionDigits:
                  1,
              }
            )
          }
        />

        <SummaryCard
          label="Total Labor-Hours"
          value={
            formatNumber(
              totals.totalLaborHours,
              {
                maximumFractionDigits:
                  1,
              }
            )
          }
        />
      </View>

      {workforce.length ===
      0 ? (
        <EmptyState
          title="No workforce records"
          text="No crews or workforce roles were recorded for this Daily Report."
        />
      ) : (
        workforce.map(
          (
            crew,
            crewIndex
          ) => {
            const roles =
              crew.roles ||
              crew.workforce_roles ||
              [];

            return (
              <View
                key={
                  crew.id ||
                  crewIndex
                }
                wrap={false}
                style={{
                  marginBottom: 10,
                }}
              >
                <View
                  style={
                    pdfStyles.table
                  }
                >
                  <View
                    style={
                      pdfStyles.tableHeader
                    }
                  >
                    <HeaderCell width="24%">
                      Company
                    </HeaderCell>

                    <HeaderCell width="22%">
                      Crew
                    </HeaderCell>

                    <HeaderCell width="22%">
                      Supervisor
                    </HeaderCell>

                    <HeaderCell width="16%">
                      Regular h
                    </HeaderCell>

                    <HeaderCell width="16%">
                      OT h
                    </HeaderCell>
                  </View>

                  <TableRow>
                    <TableCell
                      width="24%"
                      strong
                    >
                      {crew.company_name}
                    </TableCell>

                    <TableCell width="22%">
                      {crew.crew_name}
                    </TableCell>

                    <TableCell width="22%">
                      {crew.supervisor_name}
                    </TableCell>

                    <TableCell width="16%">
                      {formatNumber(
                        crew.regular_hours,
                        {
                          maximumFractionDigits:
                            1,
                        }
                      )}
                    </TableCell>

                    <TableCell width="16%">
                      {formatNumber(
                        crew.overtime_hours,
                        {
                          maximumFractionDigits:
                            1,
                        }
                      )}
                    </TableCell>
                  </TableRow>
                </View>

                {roles.length >
                  0 && (
                  <View
                    style={{
                      marginTop: 4,
                    }}
                  >
                    {roles.map(
                      (
                        role,
                        roleIndex
                      ) => (
                        <Text
                          key={
                            role.id ||
                            roleIndex
                          }
                          style={
                            pdfStyles.sectionDescription
                          }
                        >
                          {safeText(
                            role.role_name
                          )}
                          {' · '}
                          {formatNumber(
                            role.worker_count,
                            {
                              maximumFractionDigits:
                                0,
                            }
                          )}{' '}
                          workers
                        </Text>
                      )
                    )}
                  </View>
                )}
              </View>
            );
          }
        )
      )}
    </View>
  );
}

function ProductionSection({
  production,
}) {
  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="04"
        title="Production"
        description="Production recorded by project location and service."
      />

      {production.length ===
      0 ? (
        <EmptyState
          title="No production records"
          text="No production quantities were recorded for this Daily Report."
        />
      ) : (
        <View
          style={
            pdfStyles.table
          }
        >
          <View
            style={
              pdfStyles.tableHeader
            }
          >
            <HeaderCell width="20%">
              Location
            </HeaderCell>

            <HeaderCell width="18%">
              Service
            </HeaderCell>

            <HeaderCell width="10%">
              Plan
            </HeaderCell>

            <HeaderCell width="10%">
              Actual
            </HeaderCell>

            <HeaderCell width="12%">
              Cum.
            </HeaderCell>

            <HeaderCell width="12%">
              Progress
            </HeaderCell>

            <HeaderCell width="18%">
              Status
            </HeaderCell>
          </View>

          {production.map(
            (
              item,
              index
            ) => {
              const progress =
                getProductionProgress(
                  item.cumulative_quantity,
                  item.scope_quantity
                );

              const variance =
                getVariance(
                  item.planned_quantity,
                  item.actual_quantity
                );

              let tone;

              if (
                variance !==
                  null &&
                variance <
                  0
              ) {
                tone =
                  'warning';
              }

              if (
                item.production_status ===
                'completed'
              ) {
                tone =
                  'success';
              }

              return (
                <TableRow
                  key={
                    item.id ||
                    index
                  }
                  alternate={
                    index % 2 ===
                    1
                  }
                >
                  <TableCell
                    width="20%"
                    strong
                  >
                    {item.location_name}
                  </TableCell>

                  <TableCell width="18%">
                    {item.service_name}
                  </TableCell>

                  <TableCell width="10%">
                    {formatQuantity(
                      item.planned_quantity,
                      item.unit
                    )}
                  </TableCell>

                  <TableCell width="10%">
                    {formatQuantity(
                      item.actual_quantity,
                      item.unit
                    )}
                  </TableCell>

                  <TableCell width="12%">
                    {formatQuantity(
                      item.cumulative_quantity,
                      item.unit
                    )}
                  </TableCell>

                  <TableCell width="12%">
                    {progress ===
                    null
                      ? '—'
                      : formatPercentage(
                          progress
                        )}
                  </TableCell>

                  <TableCell
                    width="18%"
                    tone={
                      tone
                    }
                  >
                    {formatProductionStatus(
                      item.production_status
                    )}
                  </TableCell>
                </TableRow>
              );
            }
          )}
        </View>
      )}
    </View>
  );
}

function EquipmentSection({
  equipment,
}) {
  const totals =
    calculateEquipmentTotals(
      equipment
    );

  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="05"
        title="Equipment"
      />

      <View
        style={
          pdfStyles.summaryGrid
        }
      >
        <SummaryCard
          label="Records"
          value={
            totals.records
          }
        />

        <SummaryCard
          label="Units"
          value={
            totals.units
          }
        />

        <SummaryCard
          label="Operating Hours"
          value={
            formatNumber(
              totals.operatingHours,
              {
                maximumFractionDigits:
                  1,
              }
            )
          }
          tone="success"
        />

        <SummaryCard
          label="Idle Hours"
          value={
            formatNumber(
              totals.idleHours,
              {
                maximumFractionDigits:
                  1,
              }
            )
          }
          tone={
            totals.idleHours >
            0
              ? 'warning'
              : undefined
          }
        />
      </View>

      {equipment.length ===
      0 ? (
        <EmptyState
          title="No equipment records"
          text="No equipment activity was recorded for this Daily Report."
        />
      ) : (
        <View
          style={
            pdfStyles.table
          }
        >
          <View
            style={
              pdfStyles.tableHeader
            }
          >
            <HeaderCell width="25%">
              Equipment
            </HeaderCell>

            <HeaderCell width="20%">
              Company
            </HeaderCell>

            <HeaderCell width="10%">
              Qty
            </HeaderCell>

            <HeaderCell width="15%">
              Used h
            </HeaderCell>

            <HeaderCell width="15%">
              Idle h
            </HeaderCell>

            <HeaderCell width="15%">
              Status
            </HeaderCell>
          </View>

          {equipment.map(
            (
              item,
              index
            ) => (
              <TableRow
                key={
                  item.id ||
                  index
                }
                alternate={
                  index % 2 ===
                  1
                }
              >
                <TableCell
                  width="25%"
                  strong
                >
                  {item.equipment_name}
                </TableCell>

                <TableCell width="20%">
                  {item.company_name}
                </TableCell>

                <TableCell width="10%">
                  {formatNumber(
                    item.quantity,
                    {
                      maximumFractionDigits:
                        0,
                    }
                  )}
                </TableCell>

                <TableCell width="15%">
                  {formatNumber(
                    item.hours_used,
                    {
                      maximumFractionDigits:
                        1,
                    }
                  )}
                </TableCell>

                <TableCell width="15%">
                  {formatNumber(
                    item.idle_hours,
                    {
                      maximumFractionDigits:
                        1,
                    }
                  )}
                </TableCell>

                <TableCell
                  width="15%"
                  tone={
                    item.operating_status ===
                    'operating'
                      ? 'success'
                      : 'warning'
                  }
                >
                  {formatOperatingStatus(
                    item.operating_status
                  )}
                </TableCell>
              </TableRow>
            )
          )}
        </View>
      )}
    </View>
  );
}

function MaterialsSection({
  materials,
}) {
  const totals =
    calculateMaterialTotals(
      materials
    );

  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="06"
        title="Materials"
      />

      <View
        style={
          pdfStyles.summaryGrid
        }
      >
        <SummaryCard
          label="Records"
          value={
            totals.records
          }
        />

        <SummaryCard
          label="Received"
          value={
            totals.received
          }
          tone="success"
        />

        <SummaryCard
          label="Used"
          value={
            totals.used
          }
        />

        <SummaryCard
          label="Suppliers"
          value={
            totals.suppliers
          }
        />
      </View>

      {materials.length ===
      0 ? (
        <EmptyState
          title="No material records"
          text="No material receipts or consumption records were entered."
        />
      ) : (
        <View
          style={
            pdfStyles.table
          }
        >
          <View
            style={
              pdfStyles.tableHeader
            }
          >
            <HeaderCell width="25%">
              Material
            </HeaderCell>

            <HeaderCell width="15%">
              Movement
            </HeaderCell>

            <HeaderCell width="15%">
              Quantity
            </HeaderCell>

            <HeaderCell width="20%">
              Supplier
            </HeaderCell>

            <HeaderCell width="15%">
              Reference
            </HeaderCell>

            <HeaderCell width="10%">
              Time
            </HeaderCell>
          </View>

          {materials.map(
            (
              item,
              index
            ) => (
              <TableRow
                key={
                  item.id ||
                  index
                }
                alternate={
                  index % 2 ===
                  1
                }
              >
                <TableCell
                  width="25%"
                  strong
                >
                  {item.material_name}
                </TableCell>

                <TableCell
                  width="15%"
                  tone={
                    item.movement_type ===
                    'received'
                      ? 'success'
                      : undefined
                  }
                >
                  {formatMovementType(
                    item.movement_type
                  )}
                </TableCell>

                <TableCell width="15%">
                  {formatQuantity(
                    item.quantity,
                    item.unit
                  )}
                </TableCell>

                <TableCell width="20%">
                  {item.supplier_name}
                </TableCell>

                <TableCell width="15%">
                  {item.delivery_reference}
                </TableCell>

                <TableCell width="10%">
                  {formatTime(
                    item.delivery_time
                  )}
                </TableCell>
              </TableRow>
            )
          )}
        </View>
      )}
    </View>
  );
}

function IssuesSection({
  issues,
}) {
  const totals =
    calculateIssueTotals(
      issues
    );

  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="07"
        title="Issues & Constraints"
      />

      <View
        style={
          pdfStyles.summaryGrid
        }
      >
        <SummaryCard
          label="Open Issues"
          value={
            totals.open
          }
        />

        <SummaryCard
          label="Critical"
          value={
            totals.critical
          }
          tone={
            totals.critical >
            0
              ? 'danger'
              : undefined
          }
        />

        <SummaryCard
          label="Production Impact"
          value={
            totals.impacted
          }
          tone={
            totals.impacted >
            0
              ? 'warning'
              : undefined
          }
        />

        <SummaryCard
          label="Constraint Candidates"
          value={
            totals.constraintCandidates
          }
        />
      </View>

      {issues.length ===
      0 ? (
        <EmptyState
          title="No issues recorded"
          text="No field issues or constraint candidates were recorded."
        />
      ) : (
        <View
          style={
            pdfStyles.table
          }
        >
          <View
            style={
              pdfStyles.tableHeader
            }
          >
            <HeaderCell width="22%">
              Issue
            </HeaderCell>

            <HeaderCell width="15%">
              Type
            </HeaderCell>

            <HeaderCell width="13%">
              Severity
            </HeaderCell>

            <HeaderCell width="20%">
              Location
            </HeaderCell>

            <HeaderCell width="15%">
              Impact
            </HeaderCell>

            <HeaderCell width="15%">
              Status
            </HeaderCell>
          </View>

          {issues.map(
            (
              item,
              index
            ) => (
              <TableRow
                key={
                  item.id ||
                  index
                }
                alternate={
                  index % 2 ===
                  1
                }
              >
                <TableCell
                  width="22%"
                  strong
                >
                  {item.title}
                </TableCell>

                <TableCell width="15%">
                  {formatIssueType(
                    item.issue_type
                  )}
                </TableCell>

                <TableCell
                  width="13%"
                  tone={
                    item.severity ===
                    'critical'
                      ? 'danger'
                      : item.severity ===
                          'high'
                        ? 'warning'
                        : undefined
                  }
                >
                  {formatSeverity(
                    item.severity
                  )}
                </TableCell>

                <TableCell width="20%">
                  {item.location_name}
                </TableCell>

                <TableCell
                  width="15%"
                  tone={
                    item.production_impact &&
                    item.production_impact !==
                      'none'
                      ? 'warning'
                      : undefined
                  }
                >
                  {formatProductionImpact(
                    item.production_impact
                  )}
                </TableCell>

                <TableCell width="15%">
                  {formatIssueStatus(
                    item.status
                  )}
                </TableCell>
              </TableRow>
            )
          )}
        </View>
      )}
    </View>
  );
}

function NotesSection({
  notes,
}) {
  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="08"
        title="Notes & Observations"
      />

      {notes.length ===
      0 ? (
        <EmptyState
          title="No notes recorded"
          text="No additional field observations were recorded."
        />
      ) : (
        notes.map(
          (
            note,
            index
          ) => (
            <View
              key={
                note.id ||
                index
              }
              wrap={false}
              style={{
                marginBottom:
                  8,
              }}
            >
              <View
                style={
                  pdfStyles.textBox
                }
              >
                <Text
                  style={
                    pdfStyles.textBoxTitle
                  }
                >
                  {formatNoteCategory(
                    note.category
                  )}
                  {' · '}
                  {safeText(
                    note.title,
                    `Note ${index + 1}`
                  )}
                </Text>

                {(note.location_name ||
                  note.service_name) && (
                  <Text
                    style={
                      pdfStyles.summaryHelper
                    }
                  >
                    {safeText(
                      note.location_name,
                      ''
                    )}
                    {note.location_name &&
                    note.service_name
                      ? ' · '
                      : ''}
                    {safeText(
                      note.service_name,
                      ''
                    )}
                  </Text>
                )}

                <Text
                  style={
                    pdfStyles.textBoxContent
                  }
                >
                  {safeText(
                    note.content
                  )}
                </Text>
              </View>
            </View>
          )
        )
      )}
    </View>
  );
}

function PhotoCard({
  attachment,
  index,
}) {
  const source =
    getPhotoSource(
      attachment
    );

  return (
    <View
      wrap={false}
      style={
        pdfStyles.photoColumn
      }
    >
      <View
        style={
          pdfStyles.photoCard
        }
      >
        <View
          style={
            pdfStyles.photoImageWrapper
          }
        >
          {source ? (
            <Image
              src={
                source
              }
              style={
                pdfStyles.photoImage
              }
            />
          ) : (
            <Text
              style={
                pdfStyles.emptyStateText
              }
            >
              Photo unavailable
            </Text>
          )}
        </View>

        <View
          style={
            pdfStyles.photoBody
          }
        >
          <Text
            style={
              pdfStyles.photoIndex
            }
          >
            PHOTO{' '}
            {String(
              index + 1
            ).padStart(
              2,
              '0'
            )}
          </Text>

          <Text
            style={
              pdfStyles.photoTitle
            }
          >
            {getPhotoTitle(
              attachment,
              index
            )}
          </Text>

          <Text
            style={
              pdfStyles.photoMeta
            }
          >
            {buildPhotoCaption(
              attachment
            )}
          </Text>

          {attachment.description && (
            <Text
              style={
                pdfStyles.photoDescription
              }
            >
              {
                attachment.description
              }
            </Text>
          )}
        </View>
      </View>
    </View>
  );
}

function AttachmentsSection({
  attachments,
}) {
  const totals =
    calculateAttachmentTotals(
      attachments
    );

  const {
    photos,
    otherAttachments,
  } =
    splitAttachments(
      attachments
    );

  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="09"
        title="Photos & Attachments"
        description="All photographs attached to this Daily Report are included in the PDF."
      />

      <View
        style={
          pdfStyles.summaryGrid
        }
      >
        <SummaryCard
          label="Files"
          value={
            totals.total
          }
        />

        <SummaryCard
          label="Photos"
          value={
            totals.photos
          }
          tone="success"
        />

        <SummaryCard
          label="Videos"
          value={
            totals.videos
          }
        />

        <SummaryCard
          label="Documents"
          value={
            totals.documents
          }
        />
      </View>

      {photos.length ===
      0 ? (
        <EmptyState
          title="No photos attached"
          text="No photographic documentation was attached to this Daily Report."
        />
      ) : (
        <View
          style={
            pdfStyles.photoGrid
          }
        >
          {photos.map(
            (
              attachment,
              index
            ) => (
              <PhotoCard
                key={
                  attachment.id ||
                  index
                }
                attachment={
                  attachment
                }
                index={
                  index
                }
              />
            )
          )}
        </View>
      )}

      {otherAttachments.length >
        0 && (
        <View
          style={
            pdfStyles.attachmentList
          }
        >
          <Text
            style={
              pdfStyles.sectionEyebrow
            }
          >
            OTHER ATTACHMENTS
          </Text>

          {otherAttachments.map(
            (
              attachment,
              index
            ) => (
              <View
                key={
                  attachment.id ||
                  index
                }
                style={
                  pdfStyles.attachmentRow
                }
              >
                <Text
                  style={
                    pdfStyles.attachmentName
                  }
                >
                  {safeText(
                    attachment.title ||
                      attachment.file_name
                  )}
                </Text>

                <Text
                  style={
                    pdfStyles.attachmentMeta
                  }
                >
                  {safeText(
                    attachment.attachment_type
                  )}
                  {' · '}
                  {formatFileSize(
                    attachment.file_size_bytes
                  )}
                </Text>
              </View>
            )
          )}
        </View>
      )}
    </View>
  );
}

function SafetySection({
  safety,
}) {
  if (!safety) {
    return (
      <View
        style={
          pdfStyles.section
        }
      >
        <SectionHeader
          number="10"
          title="Safety"
        />

        <EmptyState
          title="No safety record"
          text="No safety information was recorded for this Daily Report."
        />
      </View>
    );
  }

  const safetyEvents =
    Number(
      safety.incidents_count ||
        0
    ) +
    Number(
      safety.near_misses_count ||
        0
    ) +
    Number(
      safety.unsafe_conditions_count ||
        0
    );

  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="10"
        title="Safety"
      />

      <View
        style={
          pdfStyles.summaryGrid
        }
      >
        <SummaryCard
          label="Overall Status"
          value={
            formatSafetyStatus(
              safety.overall_status
            )
          }
          tone={
            safety.overall_status ===
            'normal'
              ? 'success'
              : safety.overall_status ===
                  'critical'
                ? 'danger'
                : 'warning'
          }
        />

        <SummaryCard
          label="Toolbox Talk"
          value={
            safety.toolbox_talk_held
              ? 'Held'
              : 'Not Held'
          }
        />

        <SummaryCard
          label="Inspection"
          value={
            safety.safety_inspection_completed
              ? 'Completed'
              : 'Not Completed'
          }
        />

        <SummaryCard
          label="Safety Events"
          value={
            safetyEvents
          }
          tone={
            safetyEvents >
            0
              ? 'warning'
              : 'success'
          }
        />
      </View>

      <View
        style={
          pdfStyles.infoGrid
        }
      >
        <InfoBox
          label="PPE Compliance"
          value={
            formatPpeCompliance(
              safety.ppe_compliance
            )
          }
        />

        <InfoBox
          label="Inspector"
          value={
            safety.inspector_name
          }
        />

        <InfoBox
          label="Incidents"
          value={
            safety.incidents_count ??
            0
          }
        />

        <InfoBox
          label="Near Misses"
          value={
            safety.near_misses_count ??
            0
          }
        />

        <InfoBox
          label="Unsafe Conditions"
          value={
            safety.unsafe_conditions_count ??
            0
          }
        />

        <InfoBox
          label="Stop Work Event"
          value={
            safety.stop_work_event
              ? 'Yes'
              : 'No'
          }
        />
      </View>

      <TextBox
        label="Stop Work Description"
        value={
          safety.stop_work_description
        }
      />

      <View
        style={{
          height: 6,
        }}
      />

      <TextBox
        label="Corrective Actions"
        value={
          safety.corrective_actions_summary
        }
      />

      <View
        style={{
          height: 6,
        }}
      />

      <TextBox
        label="Safety Notes"
        value={
          safety.general_notes
        }
      />
    </View>
  );
}

function ApprovalSection({
  report,
  approvalHistory,
}) {
  return (
    <View
      style={
        pdfStyles.section
      }
    >
      <SectionHeader
        number="11"
        title="Review & Approval"
      />

      <View
        style={
          pdfStyles.infoGrid
        }
      >
        <InfoBox
          label="Current Status"
          value={
            formatReportStatus(
              report?.status
            )
          }
        />

        <InfoBox
          label="Submitted"
          value={
            report?.submitted_at
              ? formatDateTime(
                  report.submitted_at
                )
              : 'No'
          }
        />

        <InfoBox
          label="Reviewed"
          value={
            report?.reviewed_at
              ? formatDateTime(
                  report.reviewed_at
                )
              : 'No'
          }
        />

        <InfoBox
          label="Approved"
          value={
            report?.approved_at
              ? formatDateTime(
                  report.approved_at
                )
              : 'No'
          }
        />
      </View>

      {approvalHistory.length ===
      0 ? (
        <EmptyState
          title="No workflow history"
          text="No approval workflow events have been recorded."
        />
      ) : (
        approvalHistory.map(
          (
            item,
            index
          ) => (
            <View
              wrap={false}
              key={
                item.id ||
                index
              }
              style={
                pdfStyles.approvalCard
              }
            >
              <Text
                style={
                  pdfStyles.approvalAction
                }
              >
                {formatApprovalAction(
                  item.action
                )}
              </Text>

              <Text
                style={
                  pdfStyles.approvalPerson
                }
              >
                {shortUserId(
                  item.performed_by
                )}
              </Text>

              <Text
                style={
                  pdfStyles.approvalDate
                }
              >
                {formatDateTime(
                  item.performed_at
                )}
              </Text>

              {item.comments && (
                <Text
                  style={
                    pdfStyles.approvalComment
                  }
                >
                  {
                    item.comments
                  }
                </Text>
              )}
            </View>
          )
        )
      )}
    </View>
  );
}

export default function DailyReportPdfDocument({
  report,
  project,

  weather = [],
  workforce = [],
  production = [],
  equipment = [],
  materials = [],
  issues = [],
  notes = [],
  attachments = [],
  safety = null,
  approvalHistory = [],
}) {
  const workforceTotals =
    calculateWorkforceTotals(
      workforce
    );

  const issueTotals =
    calculateIssueTotals(
      issues
    );

  const attachmentTotals =
    calculateAttachmentTotals(
      attachments
    );

  return (
    <Document
      title={`${formatReportNumber(
        report?.report_number
      )} · ${safeText(
        project?.name,
        'Daily Report'
      )}`}
      author="RitsuFlow"
      subject="Construction Daily Report"
      creator="RitsuFlow"
      producer="RitsuFlow"
    >
      <Page
        size="LETTER"
        style={
          pdfStyles.page
        }
        wrap
      >
        <View
          fixed
          style={
            pdfStyles.topAccent
          }
        />

        {report?.status ===
          'draft' && (
          <Text
            fixed
            style={
              pdfStyles.draftWatermark
            }
          >
            DRAFT
          </Text>
        )}

        <View
          style={
            pdfStyles.pageContent
          }
        >
          <PageHeader
            report={
              report
            }
            project={
              project
            }
          />

          <View
            style={
              pdfStyles.summaryGrid
            }
          >
            <SummaryCard
              label="Workers"
              value={
                workforceTotals.workers
              }
              tone="success"
            />

            <SummaryCard
              label="Labor-Hours"
              value={
                formatNumber(
                  workforceTotals.totalLaborHours,
                  {
                    maximumFractionDigits:
                      1,
                  }
                )
              }
            />

            <SummaryCard
              label="Production Records"
              value={
                production.length
              }
            />

            <SummaryCard
              label="Open Issues"
              value={
                issueTotals.open
              }
              tone={
                issueTotals.open >
                0
                  ? 'warning'
                  : undefined
              }
            />
          </View>

          <View
            style={
              pdfStyles.summaryGrid
            }
          >
            <SummaryCard
              label="Photos"
              value={
                attachmentTotals.photos
              }
              tone="success"
            />

            <SummaryCard
              label="Report Status"
              value={
                formatReportStatus(
                  report?.status
                )
              }
            />

            <SummaryCard
              label="Report Date"
              value={
                formatDate(
                  report?.report_date
                )
              }
            />

            <SummaryCard
              label="Work Period"
              value={
                calculateWorkPeriod(
                  report?.work_start_time,
                  report?.work_end_time
                )
              }
            />
          </View>

          <GeneralSection
            report={
              report
            }
            project={
              project
            }
          />

          <WeatherSection
            weather={
              weather
            }
          />

          <WorkforceSection
            workforce={
              workforce
            }
          />

          <ProductionSection
            production={
              production
            }
          />

          <EquipmentSection
            equipment={
              equipment
            }
          />

          <MaterialsSection
            materials={
              materials
            }
          />

          <IssuesSection
            issues={
              issues
            }
          />

          <NotesSection
            notes={
              notes
            }
          />

          <AttachmentsSection
            attachments={
              attachments
            }
          />

          <SafetySection
            safety={
              safety
            }
          />

          <ApprovalSection
            report={
              report
            }
            approvalHistory={
              approvalHistory
            }
          />
        </View>

        <Footer
          report={
            report
          }
        />
      </Page>
    </Document>
  );
}
